// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eyhukebpoggisfnrnvfq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV5aHVrZWJwb2dnaXNmbnJudmZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYwMTEzNTAsImV4cCI6MjA1MTU4NzM1MH0.zKwSeg12DjGLdbhz6npZ14c-Gp5iFIVQrJnkcOlkxh8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);